In [21]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', 0)
import matplotlib.pyplot as plt
import itertools
import random
import tqdm as tqdm

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

In [22]:
!pip install stellargraph
import stellargraph as sg
from stellargraph.data import EdgeSplitter
from stellargraph.mapper import GraphSAGELinkGenerator
from stellargraph.layer import GraphSAGE, HinSAGE, link_classification
import pandas as pd
import itertools
import tensorflow as tf
from tensorflow import keras
from sklearn import preprocessing, feature_extraction, model_selection
import numpy as np
from stellargraph import globalvar
from stellargraph import datasets
from IPython.display import display, HTML
import nltk
nltk.download('punkt')
%matplotlib inline

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [24]:
# Import transformers package from huggingface
%%capture
!pip install transformers

from transformers import AutoTokenizer, AutoModel, BertTokenizer, BertModel

In [25]:
tokenizer = AutoTokenizer.from_pretrained('allenai/scibert_scivocab_cased')

# Get the data

In [26]:
from google.colab import drive 
drive.mount('/content/drive', force_remount = True)

Mounted at /content/drive


In [27]:
## Read data in
df = pd.read_csv('drive/My Drive/Team USA/dataset_corrected.csv')

In [28]:
train_df = df.loc[:int(0.90*df.shape[0]),:]
test_df = df.loc[int(0.90*df.shape[0])+1:,:]
len_train = len(train_df)
len_test = len(test_df)

In [32]:
#constructing author graph
source = ['']
target = ['']
author_count ={}
count = 0
for index,row in train_df.iterrows():
  # if index == 100000:
  #   break
  if row['Authors'] is not np.nan and row['Citations'] is not np.nan:
    temp = row['Citations'].split(',')
    temp2  = row['Authors'].split(',')
    for i in temp:
      if int(i) <len(train_df):
        if train_df.iloc[int(i)]['Authors'] is not np.nan:
          temp3 =  train_df.iloc[int(i)]['Authors'].split(',')
          list1_permutations =list(itertools.product(temp2,temp3))
          for perm in list1_permutations:
              if perm[0] in author_count.keys():
                author_count[perm[0]]+=1
              else:
                author_count[perm[0]]=1
              if perm[1] in author_count.keys():
                author_count[perm[1]]+=1
              else:
                author_count[perm[1]]=1
              source.append(perm[0])
              target.append(perm[1])


edges = pd.DataFrame(
    {"source": source, "target": target}
)
values = pd.DataFrame(
    {'Count' : author_count.values()}, index = author_count.keys()
)

In [52]:
from stellargraph import StellarGraph
Gs = StellarGraph(values, edges)

In [53]:
from stellargraph.data import EdgeSplitter
# Define an edge splitter on the original graph G:
edge_splitter_test = EdgeSplitter(Gs)

# Randomly sample a fraction p=0.1 of all positive links, and same number of negative links, from G, and obtain the
# reduced graph G_test with the sampled links removed:
G_test, edge_ids_test, edge_labels_test = edge_splitter_test.train_test_split(
    p=0.1, method="global", keep_connected=True
)

** Sampled 323370 positive and 323370 negative edges. **


In [54]:
Citations_Graph = df['Citations'].dropna().to_dict()
citations = [(key, int(value)) for key, values in Citations_Graph.items() for value in values.split(',')]

train_citations_graph = train_df['Citations'].dropna().to_dict()
test_citations_graph = test_df['Citations'].dropna().to_dict()

train_citations = [(key, int(value)) for key, values in train_citations_graph.items() for value in values.split(',') if int(value) < len_train]
test_citations = [(key, int(value)) for key, values in test_citations_graph.items() for value in values.split(',') if int(value) > len_train]

# Get the models for the ensemble

In [55]:
class TitleBERT(nn.Module):

  def __init__(self):
    super().__init__()

    self.bertTitle = AutoModel.from_pretrained('allenai/scibert_scivocab_cased')
    self.linear = nn.Linear(768,1)

  def forward(self,inputs):

    outs = self.bertTitle(**inputs)
    outs = torch.mean(outs['last_hidden_state'],dim = 1)
    outs = self.linear(outs)
    outs = torch.sigmoid(outs)

    return outs

class VenueBERT(nn.Module):

  def __init__(self):
    super().__init__()

    self.bertVenue = AutoModel.from_pretrained('allenai/scibert_scivocab_cased')
    self.linear = nn.Linear(768,1)

  def forward(self,inputs):

    outs = self.bertVenue(**inputs)
    outs = torch.mean(outs['last_hidden_state'],dim = 1)
    outs = self.linear(outs)
    outs = torch.sigmoid(outs)

    return outs

class AbstractBERT(nn.Module):

  def __init__(self):
    super().__init__()

    self.bertAbstract = AutoModel.from_pretrained('allenai/scibert_scivocab_cased')
    self.linear = nn.Linear(768,1)

  def forward(self,inputs):

    outs = self.bertAbstract(**inputs)
    outs = torch.mean(outs['last_hidden_state'],dim = 1)
    outs = self.linear(outs)
    outs = torch.sigmoid(outs)

    return outs

In [56]:
# add model paths here to load 

# titlebert = torch.load('drive/My Drive/Team USA/models/titlebert_patsplit.pth', map_location = torch.device('cpu'))
# venuebert = torch.load('drive/My Drive/Team USA/models/venuemodel_kaggle_pat.pth', map_location = torch.device('cpu'))
# abstractbert = torch.load('drive/My Drive/Team USA/models/venuemodel_kaggle_pat.pth', map_location = torch.device('cpu'))

titlebert = torch.load('drive/My Drive/Team USA/models/titlebert_patsplit.pth')
titlebert.to(torch.device('cuda'))
venuebert = torch.load('drive/My Drive/Team USA/models/venuemodel_kaggle_pat.pth')
venuebert.to(torch.device('cuda'))
abstractbert = torch.load('drive/My Drive/Team USA/models/venuemodel_kaggle_pat.pth')
abstractbert.to(torch.device('cuda'))

VenueBERT(
  (bertVenue): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(31116, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=Tru

In [57]:
type(titlebert), type(venuebert), type(abstractbert)

(__main__.TitleBERT, __main__.VenueBERT, __main__.VenueBERT)

In [58]:
# inputs = tokenizer(['ACM Journal 33', 'ACM Journal 33'],['Institute of Manufacturing','ACM Journal 33'],return_tensors='pt',
#                     max_length = 32,
#                     truncation = True,
#                     padding = 'max_length')
# titlebert(inputs)
# venuebert(inputs)

# Dataset and Dataloader

In [59]:
class Citations(Dataset):

  def __init__(self,citations,df):
    super().__init__()
    
    self.citations = citations
    self.citations_mapping()
    self.length = df.shape[0]
    self.data = df

  def __len__(self):

    return len(self.citations)

  def citations_mapping(self):
    d = {}
    for c1, c2 in self.citations:
      if c1 not in d:
        d[c1] = []
      else:
        if c2 not in d[c1]:
          d[c1].append(c2)
    self.d = d

  def __getitem__(self,index):

    X = []
    X.append(self.data.loc[self.citations[index][0],:].values)
    X.append(self.data.loc[self.citations[index][0],:].values)
   

    Y = []
    Y.append(self.data.loc[self.citations[index][1],:].values)

    # get a random citation that is not part of that paper's citations
    rand_cit = self.citations[random.randint(0, len(self.citations)-1)][1]
    while rand_cit in self.d[self.citations[index][0]]:
      rand_cit = self.citations[random.randint(0, len(self.citations)-1)][1]

    Y.append(self.data.loc[rand_cit,:].values)


    labels = [1,0]
  
    return X,Y,labels

In [60]:
train_dataset = Citations(train_citations, df)
test_dataset = Citations(test_citations, df)

In [61]:
train_dataset[0]

([array([5,
         'Interpreting Kullback-Leibler divergence with the Neyman-Pearson lemma',
         'Shinto Eguchi,John Copas', 2006,
         'Journal of Multivariate Analysis',
         'Kullback-Leibler divergence and the Neyman-Pearson lemma are two fundamental concepts in statistics. Both are about likelihood ratios: Kullback-Leibler divergence is the expected log-likelihood ratio, and the Neyman-Pearson lemma is about error rates of likelihood ratio tests. Exploring this connection gives another statistical interpretation of the Kullback-Leibler divergence in terms of the loss of power of the likelihood ratio test when the wrong distribution is used for one of the hypotheses. In this interpretation, the standard non-negativity property of the Kullback-Leibler divergence is essentially a restatement of the optimal property of likelihood ratios established by the Neyman-Pearson lemma. The asymmetry of Kullback-Leibler divergence is overviewed in information geometry.',
        

In [62]:
train_dataset[0][0][0][2]
print(type(train_dataset))

<class '__main__.Citations'>


# Majority voting

In [63]:
def rep(s):
  if s!=s:
    return ' '
  else:
    return s.split(',')[0]

In [64]:
def custom_collate(batch):

  # batch is list of samples : batch = [dataset[0],dataset[1], and so on...]

  # lists to store titles and labels
  title1, title2, venue1, venue2, abstract1, abstract2 = [], [], [], [], [], []
  author1, author2 = [], []
  labels = []

  for sample in batch:

    title1.append(sample[0][0][1])
    title1.append(sample[1][0][1])

    venue1.append(sample[0][0][4])
    venue1.append(sample[0][1][4])

    abstract1.append(sample[0][0][5])
    abstract1.append(sample[0][1][5])

    author1.append(rep(sample[0][0][2]))#.split(',')[0])
    author1.append(rep(sample[0][1][2]))#.split(',')[0])

    title2.append(sample[1][0][1])
    title2.append(sample[1][1][1])

    venue2.append(sample[1][0][4])
    venue2.append(sample[1][1][4])

    abstract2.append(sample[1][0][5])
    abstract2.append(sample[1][1][5])

    author2.append(rep(sample[1][0][2]))#.split(',')[0])
    author2.append(rep(sample[1][1][2]))#.split(',')[0])

    labels.extend(sample[2])

  return {"title1": np.array(title1),
          "title2": np.array(title2), 
          "venue1": np.array(venue1),
          "venue2": np.array(venue2),
          "abstract1":np.array(abstract1),
          "abstract2": np.array(abstract2),
          "author2":np.array(author2),
          "author1":np.array(author1),
          "labels":labels}

In [65]:
BATCH_SIZE = 64
trainloader = DataLoader(train_dataset, collate_fn = custom_collate, batch_size = BATCH_SIZE, shuffle = False)
testloader = DataLoader(test_dataset, collate_fn = custom_collate, batch_size = BATCH_SIZE, shuffle = False)

In [66]:
import time
from tqdm import tqdm
from scipy import stats
from stellargraph import StellarGraph

def isnotnan(s):
  return s==s

In [67]:
stats.mode([0,1])[0][0]

0

In [68]:
graph_model = tf.keras.models.load_model('drive/MyDrive/Team USA/graph_model')

### Majority Voting

In [69]:
def compute_accuracy(titlemodel, venuemodel, abstractmodel, graph_model, graph, data_loader, device):
    
    titlemodel.eval()
    venuemodel.eval()
    abstractmodel.eval()
    # graph_model

    with torch.no_grad():

        correct_pred, num_examples = 0, 0

        for batch_idx, batch in enumerate(data_loader):

            print(f"{batch_idx} of {len(data_loader)}")

            # graph_author_edge = pd.read_csv('drive/MyDrive/edges.csv')
            # graph_author_value = pd.read_csv('drive/MyDrive/values.csv') 
            # Gs = StellarGraph(graph_author_value, graph_author_edge)
            test_gen = GraphSAGELinkGenerator(graph, 128, 128)
            test_ids = np.column_stack((batch['author1'], batch['author2']))
            test_flow = test_gen.flow(test_ids)
            # print(len(batch['author1']))
            # print(batch['author2'])
            # break
            start_time = time.time()

            ### Prepare data
            inputs_title = tokenizer(list(batch['title1']),list(batch['title2']),return_tensors='pt',
                    max_length = 32,
                    truncation = True,
                    padding = 'max_length')
            
            inputs_venue = tokenizer(list(batch['venue1']),list(batch['venue2']),return_tensors='pt',
                    max_length = 32,
                    truncation = True,
                    padding = 'max_length')
            
            # print(time.time() - start_time)
            
            inputs_abstract = tokenizer(list(batch['abstract1']),list(batch['abstract2']),return_tensors='pt',
                    max_length = 32,
                    truncation = True,
                    padding = 'max_length')
            
            # print(time.time() - start_time)

            inputs_title.to(device)
            inputs_venue.to(device)
            inputs_abstract.to(device)

            
            labels = torch.Tensor(batch['labels']).view(-1,1).to(device)
            
            outputs_title = titlemodel(inputs_title)
            outputs_venue = venuemodel(inputs_venue)
            outputs_abstract = abstractmodel(inputs_abstract)
            outputs_graph = graph_model.predict(test_flow)

            pred_labels_title = torch.round(outputs_title)
            pred_labels_venue = torch.round(outputs_venue)
            pred_labels_abstract = torch.round(outputs_abstract)

            # determine the locations of the nan features
            isnotnan_t = isnotnan(batch['title1']) & isnotnan(batch['title2'])
            isnotnan_v = isnotnan(batch['venue1']) & isnotnan(batch['venue2'])
            isnotnan_a = isnotnan(batch['abstract1']) & isnotnan(batch['abstract2'])

            # print(pred_labels_title)

            # -------- Majority Voting (where fields exist) --------------------
            pred_labels = []
            for i in range(len(batch['title1'])):
              res = []
              if isnotnan_t[i]:
                res.append(pred_labels_title[i].item())
              if isnotnan_v[i]:
                res.append(pred_labels_venue[i].item())
              if isnotnan_a[i]:
                res.append(pred_labels_abstract[i].item())

              pred_labels.append([stats.mode(res)[0][0]])
            pred_labels = torch.Tensor(pred_labels).to(device)
            # ---------------------------------------------

            # # -------- Averaging (where fields exist) --------------------
            # outputs_avg = []
            # for i in range(len(batch['title1'])):
            #   res = []
            #   if isnotnan_t[i]:
            #     res.append(outputs_title[i].item())
            #   if isnotnan_v[i]:
            #     res.append(outputs_venue[i].item())
            #   if isnotnan_a[i]:
            #     res.append(outputs_abstract[i].item())

            #   outputs_avg.append([np.mean(res)])
            # outputs_avg = torch.Tensor(outputs_avg).to(device)
            # pred_labels = torch.round(outputs_avg)
            # # ---------------------------------------------

            # print(pred_labels)
            # print(labels)

            num_examples += labels.size(0)

            correct_pred += (pred_labels == labels).sum()

            print(correct_pred.float()/num_examples * 100)
    return correct_pred.float()/num_examples * 100

In [70]:
# compute_accuracy(titlebert, venuebert, abstractbert, trainloader, 'cpu')
compute_accuracy(titlebert, venuebert, abstractbert,graph_model, G_test, trainloader, 'cuda')

0 of 7879


ValueError: ignored

In [ ]:
# compute_accuracy(titlebert, venuebert, abstractbert, testloader, 'cpu')
compute_accuracy(titlebert, venuebert, abstractbert, testloader, 'cuda')

### Average ensemble

In [ ]:
def compute_accuracy(titlemodel, venuemodel, abstractmodel, data_loader, device):
    
    titlemodel.eval()
    venuemodel.eval()
    abstractmodel.eval()

    with torch.no_grad():

        correct_pred, num_examples = 0, 0

        for batch_idx, batch in enumerate(data_loader):

            print(f"{batch_idx} of {len(data_loader)}")

            # print(batch['venue1'])
            

            start_time = time.time()

            ### Prepare data
            inputs_title = tokenizer(list(batch['title1']),list(batch['title2']),return_tensors='pt',
                    max_length = 32,
                    truncation = True,
                    padding = 'max_length')
            
            inputs_venue = tokenizer(list(batch['venue1']),list(batch['venue2']),return_tensors='pt',
                    max_length = 32,
                    truncation = True,
                    padding = 'max_length')
            
            # print(time.time() - start_time)
            
            inputs_abstract = tokenizer(list(batch['abstract1']),list(batch['abstract2']),return_tensors='pt',
                    max_length = 32,
                    truncation = True,
                    padding = 'max_length')
            
            # print(time.time() - start_time)

            inputs_title.to(device)
            inputs_venue.to(device)
            inputs_abstract.to(device)

            
            labels = torch.Tensor(batch['labels']).view(-1,1).to(device)
            
            outputs_title = titlemodel(inputs_title)
            outputs_venue = venuemodel(inputs_venue)
            outputs_abstract = abstractmodel(inputs_abstract)

            pred_labels_title = torch.round(outputs_title)
            pred_labels_venue = torch.round(outputs_venue)
            pred_labels_abstract = torch.round(outputs_abstract)

            # determine the locations of the nan features
            isnotnan_t = isnotnan(batch['title1']) & isnotnan(batch['title2'])
            isnotnan_v = isnotnan(batch['venue1']) & isnotnan(batch['venue2'])
            isnotnan_a = isnotnan(batch['abstract1']) & isnotnan(batch['abstract2'])

            # print(pred_labels_title)

            # # -------- Majority Voting (where fields exist) --------------------
            # pred_labels = []
            # for i in range(len(batch['title1'])):
            #   res = []
            #   if isnotnan_t[i]:
            #     res.append(pred_labels_title[i].item())
            #   if isnotnan_v[i]:
            #     res.append(pred_labels_venue[i].item())
            #   if isnotnan_a[i]:
            #     res.append(pred_labels_abstract[i].item())

            #   pred_labels.append([stats.mode(res)[0][0]])
            # pred_labels = torch.Tensor(pred_labels).to(device)
            # # ---------------------------------------------

            # -------- Averaging (where fields exist) --------------------
            outputs_avg = []
            for i in range(len(batch['title1'])):
              res = []
              if isnotnan_t[i]:
                res.append(outputs_title[i].item())
              if isnotnan_v[i]:
                res.append(outputs_venue[i].item())
              if isnotnan_a[i]:
                res.append(outputs_abstract[i].item())

              outputs_avg.append([np.mean(res)])
            outputs_avg = torch.Tensor(outputs_avg).to(device)
            pred_labels = torch.round(outputs_avg)
            # ---------------------------------------------

            # print(pred_labels)
            # print(labels)

            num_examples += labels.size(0)

            correct_pred += (pred_labels == labels).sum()

            print(correct_pred.float()/num_examples * 100)
    return correct_pred.float()/num_examples * 100

In [ ]:
# compute_accuracy(titlebert, venuebert, abstractbert, testloader, 'cpu')
compute_accuracy(titlebert, venuebert, abstractbert, testloader, 'cuda')

0 of 128
tensor(81.2500, device='cuda:0')
1 of 128
tensor(82.8125, device='cuda:0')
2 of 128
tensor(83.0729, device='cuda:0')
3 of 128
tensor(82.6172, device='cuda:0')
4 of 128
tensor(81.2500, device='cuda:0')
5 of 128
tensor(80.8594, device='cuda:0')
6 of 128
tensor(80.4688, device='cuda:0')
7 of 128
tensor(79.8828, device='cuda:0')
8 of 128
tensor(79.8611, device='cuda:0')
9 of 128
tensor(80.2344, device='cuda:0')
10 of 128
tensor(80.1136, device='cuda:0')
11 of 128
tensor(80.4688, device='cuda:0')
12 of 128
tensor(80.7091, device='cuda:0')
13 of 128
tensor(80.4129, device='cuda:0')
14 of 128
tensor(80.3125, device='cuda:0')
15 of 128
tensor(79.9805, device='cuda:0')
16 of 128
tensor(80.3309, device='cuda:0')
17 of 128
tensor(80.0347, device='cuda:0')
18 of 128
tensor(79.9342, device='cuda:0')
19 of 128
tensor(79.6094, device='cuda:0')
20 of 128
tensor(79.5759, device='cuda:0')
21 of 128
tensor(79.7940, device='cuda:0')
22 of 128
tensor(80.1291, device='cuda:0')
23 of 128
tensor(80.0

tensor(79.2290, device='cuda:0')

# Run a forward pass on sample input

In [ ]:
ind = 17 
p1 = df.iloc[17]

cits = df['Citations'][ind]
cits = cits.split(',')
cits = [int(c) for c in cits]

for c in cits:
  print(c)
  p2 = df.iloc[c]
  
  inputs_title = tokenizer([p1['Title']], [p2['Title']], return_tensors = 'pt',
                           max_length = 32, truncation = True, padding = 'max_length')
  print(titlebert(inputs_title))
  
  if type(p1['Venue'])==str and type(p2['Venue'])==str:
    inputs_venue = tokenizer([p1['Venue']], [p2['Venue']], return_tensors = 'pt',
                            max_length = 32, truncation = True, padding = 'max_length')
    print(venuebert(inputs_venue))
  
  


357875
tensor([[0.9623]], grad_fn=<SigmoidBackward0>)
tensor([[0.6248]], grad_fn=<SigmoidBackward0>)
214023
tensor([[0.9941]], grad_fn=<SigmoidBackward0>)
tensor([[0.9963]], grad_fn=<SigmoidBackward0>)
317448
tensor([[0.9946]], grad_fn=<SigmoidBackward0>)
tensor([[0.9956]], grad_fn=<SigmoidBackward0>)
319987
tensor([[0.9871]], grad_fn=<SigmoidBackward0>)
tensor([[0.6522]], grad_fn=<SigmoidBackward0>)
334185
tensor([[0.9861]], grad_fn=<SigmoidBackward0>)
tensor([[0.7613]], grad_fn=<SigmoidBackward0>)
95255
tensor([[0.9748]], grad_fn=<SigmoidBackward0>)
294124
tensor([[0.3765]], grad_fn=<SigmoidBackward0>)
tensor([[0.8313]], grad_fn=<SigmoidBackward0>)
96319
tensor([[0.0501]], grad_fn=<SigmoidBackward0>)
tensor([[0.1989]], grad_fn=<SigmoidBackward0>)
610127
tensor([[0.9993]], grad_fn=<SigmoidBackward0>)
tensor([[0.9962]], grad_fn=<SigmoidBackward0>)


In [ ]:
# Averaging ensemble

prob = []

for idx1, idx2 in tqdm(test_citations):

  # get the two papers
  p1 = df.iloc[idx1]
  p2 = df.iloc[idx2]

  res = []

  # title will always exist (I think??)
  inputs_title = tokenizer([p1['Title']], [p2['Title']], return_tensors = 'pt',
                           max_length = 32, truncation = True, padding = 'max_length')
  res.append(titlebert(inputs_title).item())
  
  if type(p1['Venue'])==str and type(p2['Venue'])==str:
    inputs_venue = tokenizer([p1['Venue']], [p2['Venue']], return_tensors = 'pt',
                            max_length = 32, truncation = True, padding = 'max_length')
    # print(venuebert(inputs_venue))
    res.append(venuebert(inputs_venue).item())

  prob.append(np.mean(res))
  # print(np.mean(res))



print(prob)

  



[0.9102713167667389, 0.4544652998447418, 0.5327351689338684, 0.7293183207511902, 0.7384950518608093, 0.858288586139679, 0.9193280339241028, 0.9970178604125977, 0.9317418038845062, 0.8895634710788727, 0.8271278142929077, 0.757253110408783, 0.8239882290363312, 0.665449246764183, 0.14407627284526825, 0.9084127843379974, 0.9106732308864594, 0.9390210807323456, 0.22672046720981598, 0.979086697101593, 0.9682144522666931, 0.5376552641391754, 0.394911527633667, 0.8768737018108368, 0.6421718597412109, 0.999293327331543, 0.6416687965393066, 0.5108339190483093, 0.7773755490779877, 0.9958547949790955, 0.6665770411491394, 0.9948846697807312, 0.9737203121185303, 0.9745980501174927, 0.994413435459137, 0.8615728914737701, 0.9912108182907104, 0.999254047870636, 0.939901202917099, 0.8948940634727478, 0.9845825433731079, 0.9923205971717834, 0.9995452761650085, 0.9937540888786316, 0.5401720404624939, 0.9878716468811035, 0.9829439520835876, 0.9723591208457947, 0.8204454481601715, 0.9447020590305328, 0.8528

In [ ]:
np.mean(prob)

0.7968190245625406